### ISSUE TITLE
Building without depending on libboost?

### ISSUE THREAD

**Issue by vanfanel** [lethal-guitar/RigelEngine#662] opened 2021-03-20 17:54 UTC
Hi there, @lethal-guitar !

On my continuing mission for native engines to try on SDL2/KMSDRM (SDL2 with no X11 depencencies!), I have just found this engine, and looks & sounds awesome on videos.

So I have tried to build it but seems to depend on boost, which is a HUGE lib!
Is there a way to build without depending on it? Checked CMakeLists.txt, but couldn't find a thing about it...

And, since it seems to run on OGA machines, I believe it must me possible to build without the heavy BOOST dependencies.

Thanks!

Manuel

EDIT: Even after installing libboost-dev, I still get this with `cmake -DUSE_GL_ES=ON -DCMAKE_BUILD_TYPE=Release ..`

```
manuel@hp15db0:~/src/RigelEngine/b4$ cmake -DUSE_GL_ES=ON -DCMAKE_BUILD_TYPE=Release ..
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by
  "boost_program_options" (requested version 1.71.0) with any of the
  following names:

    boost_program_optionsConfig.cmake
    boost_program_options-config.cmake

  Add the installation prefix of "boost_program_options" to CMAKE_PREFIX_PATH
  or set "boost_program_options_DIR" to a directory containing one of the
  above files.  If "boost_program_options" provides a separate development
  package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:53 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/manuel/src/RigelEngine/b4/CMakeFiles/CMakeOutput.log".
```

**Comment by lethal-guitar** [comment] 2021-03-20 19:58
Hi @vanfanel, happy to hear you're interested in the project!

RigelEngine runs pretty well on the KMSDRM backend, and it also runs without X on Raspberry Pis using the RPI backend. But the code is still compiled with Boost in all those cases. I'll say more about it in a sec 🙂

But first, regarding the build error: You additionally need to install `libboost-program-options-dev`. The package `libboost-dev` only installs the header-only parts of Boost, but the program options library has a compiled component and thus needs a library to be installed as well, which that separate package does.

This is definitely not ideal, and I'm planning to replace the program options library with something else more lightweight. There's already #192 to keep track of that task. But haven't gotten around to it yet, unfortunately.

Now, regarding Boost in general: I totally agree that Boost as a whole is gigantic, and some parts of it suffer from a lot of cruft and overly complex designs. Not to mention that its documentation is often severely lacking.

But depending on some Boost libraries doesn't mean that all of Boost gets pulled into the compiled binary. Many of the libraries in Boost are header only, and compile down to efficient machine code that doesn't depend on any library at run-time. I fully agree that having all of Boost on the target machine would be a problem. But with RigelEngine, it's only needed during compilation, the compiled binary doesn't depend on any Boost libraries. And we can use cross-compilation to target less powerful machines.

At the same time, I also agree in general that fewer dependencies are better 🙂 And not having to install Boost for compiling the project would be nice. So let's see, could the Boost dependency be dropped completely? I think so, it's just a little bit of work.

What am I using Boost for?

* Command line arg parsing, using the program options library. As I mentioned, this one is something I'm not really happy with and already looking to replace with something else.
* String utilities, mainly stripping and splitting etc. It's convenient to have these utilities available, but it probably wouldn't be too much work to replace them with something homegrown.
* `static_vector`. This is quite useful to have for performance reasons, but I would expect there to be more lightweight alternatives around that we could simply drop into the `3rd_party` folder.

So overall, that's not too many things, and it seems doable to get rid of Boost. But it would be a little bit of work still, and I'm more focused on usability improvements at the moment. Any contributions in that area would be very welcome though 😉

**Comment by vanfanel** [comment] 2021-03-21 16:33
@lethal-guitar 

Thanks for your answer!
I just built (after the libboost-program-options-dev dependency was satisfied) and tried on SDL2/KMSDRM, and indeed it works great :)

I would like to help with the libboost removal effort, but I am currently swamped under a lot of work, and my free code efforts are concentrated on SDL2/KMSDRM, which I am still improving. But I will test any progress on that front! It's a VERY good engine, and IMHO it shouldn't have big dependencies like that.

**Comment by lethal-guitar** [comment] 2021-03-28 11:10
[This](https://github.com/gnzlbg/static_vector) looks like a good candidate for replacing `boost::static_vector`.

**Comment by vanfanel** [comment] 2021-03-28 19:21
@lethal-guitar Yes, looks like a great option!
I guess there's still the string utilities remaining then?

**Comment by lethal-guitar** [comment] 2021-03-28 19:37
@vanfanel exactly. And those shouldn't be too hard to implement using just std library stuff, I think. Since it's just trimming and splitting.

**Comment by vanfanel** [comment] 2021-07-21 15:09
@lethal-guitar Tried to build today on a system without libboost installed, and it's still looking for it. Maybe I am doing something wrong?

**Comment by lethal-guitar** [comment] 2021-07-21 15:19
@vanfanel unfortunately, the Boost removal is currently stuck on #665, which in turn is stuck waiting for a fix in another library.. So for the time being, Boost is still needed, sorry about that.

You could comment out the command line parsing code in `main.cpp` and remove the `find_package` call as a temporary workaround? There's one more place in the code where a boost function is used but even that could be commented out without impacting most of the functionality.

I can push a branch with all these changes later today.

**Comment by vanfanel** [comment] 2021-07-21 16:39
@lethal-guitar What about #ifdef-ing the features using BOOST instead of a new branch? Then simply passing something like `-DHAVE_BOOST=false` would be used to build a BOOST-less version.

**Comment by lethal-guitar** [comment] 2021-07-21 19:19
@vanfanel good idea! Check out #701, it should build and function without Boost.

**Comment by vanfanel** [comment] 2021-07-22 09:55
@lethal-guitar Great! I built and tested the `make-boost-optional` on the Pi4 (aarch64) and works without boost!

However, the game seems to hang when I chose the "Game Options" menu entry and press ENTER.
Can you reproduce that?

**Comment by lethal-guitar** [comment] 2021-07-22 11:43
@vanfanel cool, I'll merge that PR then.

Regarding the options menu, this sounds like it might be an OpenGL issue - I can't reproduce it but I don't have a Pi4. Is this with OpenGL ES or regular OpenGL? On the AArch64-based systems I have (OGA, OGS), I'm using GL ES, but IIRC the Pi 4 also offers Desktop GL. 

Any chance you could run it with `gdb` and get a stack trace?

**Comment by vanfanel** [comment] 2021-07-22 16:27
@lethal-guitar I have built a GLES version like this:

`cmake -DUSE_GL_ES=ON -DCMAKE_BUILD_TYPE=Debug ..`

About GDB and bt, the problem is that GDB doesn't respond to CTRL+C when the game gets stuck after I chose Game Options:
```

(gdb) r
Starting program: /home/pi/dn2/RigelEngine 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
================================================================================
                            Welcome to RIGEL ENGINE!

  A modern reimplementation of the game Duke Nukem II, originally released in
  1993 for MS-DOS by Apogee Software.

You need the original game's data files in order to play, e.g. the freely
available shareware version.

Rigel Engine Copyright (C) 2016, Nikolai Wuttke.
Rigel Engine comes with ABSOLUTELY NO WARRANTY. This is free software, and you
are welcome to redistribute it under certain conditions.
For details, see https://www.gnu.org/licenses/gpl-2.0.html
================================================================================

[New Thread 0x7ff78601c0 (LWP 454)]
[New Thread 0x7ff55b81c0 (LWP 455)]
^C
```

**Comment by lethal-guitar** [comment] 2021-07-22 18:02
@vanfanel huh, ok that's interesting.. So the game doesn't respond to any input anymore, but still runs? Does the screen keep showing the main menu, or does it go black?

I'm not sure yet what the problem could be, I'll have to think about it..

In the meantime, you can also edit the config file directly if you'd like to change some options: https://github.com/lethal-guitar/RigelEngine/wiki/FAQ#where-are-saved-games-settings-etc-stored

**Comment by lethal-guitar** [comment] 2021-07-22 18:05
@vanfanel did a quick search on what to do if Ctrl+C in gdb doesn't work, maybe worth a shot: https://stackoverflow.com/a/41516930

**Comment by vanfanel** [comment] 2021-07-22 18:32
@lethal-guitar Thing is, I can't even do `gdb attach <PID>`, because GDB won't even be able to attach when the game is hung:

```
pi@raspberrypi:~ $ ps -a
  PID TTY          TIME CMD
  332 tty1     00:00:00 bash
  333 tty2     00:00:00 bash
  442 tty1     00:00:07 RigelEngine
  453 pts/0    00:00:00 ps
pi@raspberrypi:~ $ gdb attach 442
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
attach: No such file or directory.
Attaching to process 442
```

The game keeps showing the MAIN MENU, that's what it does.

**Comment by vanfanel** [comment] 2021-07-22 18:57
@lethal-guitar Forget about this strange issue! Options menu now works, after (brace yourself!) going back to the stable Pi4 kernel instead of using the bleeding-edge version!

https://github.com/raspberrypi/firmware/issues/1598

**Comment by lethal-guitar** [comment] 2021-07-22 19:25
@vanfanel oh wow ok! Well happy to hear it's working now 🙂

**Comment by vanfanel** [comment] 2021-07-22 19:50
@lethal-guitar Can I ask for a small feature? Bilinear interpolation, which can be simply activated with `SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, "linear");`
and a small option for it.

**Comment by lethal-guitar** [comment] 2021-07-22 20:25
@vanfanel sure! The SDL hint only works when using the SDL rendering API, it has no effect when using OpenGL directly. But it's fairly easy to do with OpenGL as well.

I personally prefer the non-interpolated look, but I'm happy to add an option for it.

**Comment by vanfanel** [comment] 2021-07-22 21:32
@lethal-guitar Thanks! I will test it as soon as it's available (I prefer a bit of a blurry look, like old CRTs..)

**Comment by vanfanel** [comment] 2021-07-23 09:13
@lethal-guitar As a curiosity, if you go to level 3 (or the last part of level 2) with the scrolling clouds, using the current "nearest" scaling you will see there's that "crawling" effect on the fine scrolling. With "bilinear", that would go away, too! :)

**Comment by lethal-guitar** [comment] 2021-07-23 10:36
@vanfanel I do like CRTs as well! I've been planning to integrate some CRT emulation shaders for a while, but haven't gotten around to it yet.

The artifacts with autoscrolling backgrounds you mention are definitely not ideal and also something I would like to fix. You're right that linear scaling would prevent them. 🙂 I also have some ideas that would work even with nearest neighbor scaling, but that's another thing I haven't gotten around to.

**Comment by vanfanel** [comment] 2021-07-23 10:45
@lethal-guitar This project has awesome (and very light!) CRT simulation.
And the guy behind it is very nice to talk to!
https://github.com/drfiemost/Hurrican
I recommend you to build it and run it with the --crt option, you will be very surprised! It even has a curvature effect.

**Comment by lethal-guitar** [comment] 2021-07-23 11:31
@vanfanel ah nice one, thanks for the pointer, I'll check it out! I quite enjoyed Hurrican back in the day, happy to see it's still being developed

**Comment by lethal-guitar** [comment] 2021-07-23 12:35
@vanfanel getting back to this issue, after #702 is merged, the game will be pretty much fully usable without Boost - only the various debugging features won't be available, since they are activated via command line arguments. But these are mostly interesting for actively developing the game. And once I replace the options parsing with another library, the functionality will be available without Boost as well.

Would you be ok with closing this issue now, or would you prefer I leave it open until #665 is merged as well?

**Comment by vanfanel** [comment] 2021-07-23 13:47
@lethal-guitar I think it should be closed, as there is no issue anymore really :)

**Closed** 2021-07-23 13:47 UTC
Labels: dev

**Comment by lethal-guitar** [comment] 2021-07-31 11:28
@vanfanel I've pushed a branch `filtering-test` with bilinear blending enabled. To me, it looks much too blurry, but maybe this is roughly what you were looking for me? Let me know and I'll add it as an option

**Comment by vanfanel** [comment] 2021-07-31 13:34
@lethal-guitar It looks very good to me, just like on a CRT :)
Please add it as an option. I love how it moves now on the 3rd level background!
